spring:
  application:
    name: eshop-config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: /Users/gao/Documents/workspace/hpe/MicroService/SpringCloud-eShop/config-server/repository/{application}
        git:
          uri: https://github.com/hpeu-china/MicroService
          searchPaths: /SpringCloud-eShop/config-server/repository/{application}
#          basedir: repository
#          username:
#          password:
#      label: master
info:
  app:
    name: ${spring.application.name}
    version: v1.0.0
server:
  port: 8051
  context-path: /
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:logback.xml
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8030/eureka/