spring:
  application:
    name: ribbon-provider
info:
  app:
    name: ${spring.application.name}
    version: v1.0.0
logging:
  config: classpath:logback.xml
server:
  context-path: /
  tomcat:
    uri-encoding: UTF-8    
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8030/eureka/
---
spring:
  profiles: provider1
server:
  port: 8071
---
spring:
  profiles: provider2
server:
  port: 8072
---
spring:
  profiles: provider3
server:
  port: 8073