spring:
  application:
    name: eshop-zuul-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    #password:
  zipkin:
    base-url: http://127.0.0.1:8053
info:
  app:
     name: ${spring.application.name}
     version: v1.0.0
server:
  port: 8031
  context-path: /
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:logback.xml
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8030/eureka/

zuul:
  ribbon-isolation-strategy: THREAD # SEMAPHORE THREAD
  sensitive-headers:
  ignored-headers:
  ignored-services: '*'
  retryable: true
  routes:
    nginxa:
      path: /service-a/**
      url: http://127.0.0.1:8080
    nginxb:
      path: /service-b/**
      url: http://127.0.0.1:8081
    feign:
      path: /feign/**
      url: forward:/feign
    session:
      path: /session/**
      url: forward:/session
    account:
      path: /account/**
      serviceId: eshop-auth-service
      stripPrefix: false
    product:
      path: /products/**
      serviceId: eshop-product-service
      stripPrefix: false
    cart:
      path: /cart/**
      serviceId: eshop-cart-service
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  restclient:
    enabled: true