spring:
  application:
    name: eshop-eureka-server
info:
  app:
    name: ${spring.application.name}
    version: v1.0.0
logging:
  config: classpath:logback.xml
server:
  port: 8043
  context-path: /
  tomcat:
    uri-encoding: UTF-8    
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8041/eureka/,http://127.0.0.1:8042/eureka/,http://127.0.0.1:8043/eureka/